theme: minima
title: Projet IHM
author: Jules Boudon, Thomas Hebert, Loona Macabre, Amélie Sun
description: Le projet consiste à concevoir, évaluer et reconcevoir un système interactif sous la forme d’un prototype vidéo. Le système devra répondre aux besoins d’utilisateurs réels dans un contexte réel. Cette année, on choisira une application de cartes (Google Maps ou ...?)
base: main
compare: my-pages
